name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_ROCK_0E9D7CC03 }}
          action: 'upload'
          production_branch: 'main'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: 'npm run docs:build'
          app_location: '/'
          api_location: ''
          output_location: '.vitepress/dist'
          is_static_export: true
          ###### End of Repository/Build Configurations ######
          